version: '3'
services:
  server-api-db:
    build: ./db
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - server-api-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  server-api-volume: