CREATE TABLE IF NOT EXISTS products (
    id SERIAL NOT NULL PRIMARY KEY UNIQUE,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    image VARCHAR(255) NOT NULL UNIQUE,
    price DECIMAL NOT NULL,
    quantity INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT NOW()
);